---
- name: Boiler Thermia S2
  price: 30000
  unit: tk
- name: Boiler Thermia Libra
  price: 45000
  unit: tk
- name: Küttetoru
  price: 10
  unit: mm
- name: Insulaator küttetoru jaoks
  price: 5
  unit: mm
